# Eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true

# Management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
# zipkin
  zipkin:
    baseUrl: http://zipkin:9411
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
