spring:

  kafka:
    bootstrap-server: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: password

server:
  servlet:
    context-path: /connections
  port: 9030

