spring:
    
  kafka:
    bootstrap-server: 172.22.154.68:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      
  datasource:
    url: jdbc:postgresql://posts_db:5432/linkedin
    username: shashank
    password: shashank
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true

server:
  port: 8000
  servlet:
    context-path: /posts
