spring:

  datasource:
    url: jdbc:postgresql://postgres_container:5432/linkedin
    username: shashank
    password: shashank
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true

server:
  port: 8082
  servlet:
    context-path: /users
